Adjusted Stardew YAML to force progressive goals on based on slot's goal.
ArchipelagoMW/AsyncTools pull request #185
Opened 2024-08-28 11:54 UTC by ploki122

Added triggers to ensure that the most egregious cases don't happen (like rolling craftmaster without craftsanity checks). This makes it so working toward your goal will explicitly send checks.

2024-08-28 16:23 UTC, agilbert1412 requested changes

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +      option_result: community_center
Suggestion: if CC goal is rolled, vanilla bundle odds should be transferred to either remixed or thematic. Vanilla CC is boring as a goal I think

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +            all: 10
I would also move the "only easy fish" odds to all, for a total of 30-20-50

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          museumsanity: #remove none odds
Can we scale that to 75-25, just to maintain consistency with the rest of the yaml where odds are built as a percentage?

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          shipsanity: #Remove none odds
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          shipsanity: #Remove none odds
Can we split this a bit, to maybe include some fish options too? I'm still against the "everything" setting for a yaml, but the other ones would bring a bit of variety

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          cooksanity: #Remove none odds
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          chefsanity: #Increase the odds shuffling recipes to add
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          craftsanity: #Remove none odds
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          monstersanity:
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          museumsanity: #Remove none odds
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          festival_locations: #Remove disable odds
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          friendsanity: #Remove none odds
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          fishsanity: #Set to all, since that is required
Scaling to 100

2024-08-28 16:23 UTC, agilbert1412 commented on games/Stardew Valley.yaml
> +          fishsanity: #Set to all, since that is required
Fishsanity doesn't need to be "all" to shuffle the stardrop. The stardrop is quite literally the only item generated from fishsanity, so no matter how many locations are added by it, the stardrop always shuffles. You can keep odds for other settings pretty much the same, as long as it's not "none"

2024-08-28 16:59 UTC, ploki122 commented on games/Stardew Valley.yaml
> +      option_result: community_center
I feel like vanilla bundles should either be removed entirely from the YAML, or that CC goal should have them. Either the vanilla bundle is fun or it's not, and I don't think Vanilla is meaningfully shorter or less varied than remixed/thematic.

2024-08-29 02:22 UTC, ploki122 commented on games/Stardew Valley.yaml
> +          shipsanity: #Remove none odds
My opinion is the same for this and CC : If it's worth changing shipsanity for full_shipment, it's probably worth changing it for the entire YAML. In this case, however, I prefer changing it for the entire YAML.

2024-09-03 14:56 UTC, agilbert1412 approved these changes

2024-09-04 00:10 UTC, merged