Updates to SMZ3 and SM64, adding DKC3
ArchipelagoMW/AsyncTools pull request #30
Opened 2022-08-09 22:51 UTC by ScootyPuffJr1

2022-08-10 12:12 UTC, Marechal-L commented on games/Dark Souls III.yaml
> +    ["Small Lothric Banner","Cinders of a Lord - Abyss Watcher","Cinders of a Lord - Yhorm the Giant","Cinders of a Lord - Aldrich","Cinders of a Lord - Lothric Prince"]
Just to make sure to understand properly,
You are forcing the "Small Lothric Banner" to be local to prevent from being stucked early ?
And because the "Small Doll" is a late-game item you do not apply the same condition to it, right ?

2022-08-10 12:12 UTC, Marechal-L commented on games/Dark Souls III.yaml
> +    true: 2
If you want to make it easier than harder, I would suggest to swap the weight of "no_weapon_requirements" and "randomize_weapons_level" unless they are the intended values.

Otherwise, everything looks great!

2022-08-10 12:34 UTC, ScootyPuffJr1 commented on games/Dark Souls III.yaml
> +    ["Small Lothric Banner","Cinders of a Lord - Abyss Watcher","Cinders of a Lord - Yhorm the Giant","Cinders of a Lord - Aldrich","Cinders of a Lord - Lothric Prince"]
It's my understanding that Small Lothric Banner is similar to a moon pearl from LttP in that it creates an early gate for a wide portion of the game. Forcing it local should allow for more early checks if that's the case.

2022-08-10 13:34 UTC, ScootyPuffJr1 commented on games/Dark Souls III.yaml
> +    true: 2
I swapped those two, per your suggestion.

2022-08-10 15:00 UTC, Marechal-L commented on games/Dark Souls III.yaml
> +    ["Small Lothric Banner","Cinders of a Lord - Abyss Watcher","Cinders of a Lord - Yhorm the Giant","Cinders of a Lord - Aldrich","Cinders of a Lord - Lothric Prince"]
That's right, so I approve this setting!

2022-08-10 15:02 UTC, Marechal-L commented
My comments are resolved ( but I unfortunately can't approve this pull-request myself )

2022-08-10 18:13 UTC, Berserker66 commented
because this is a PR for many games we need the ok from all games first.

2022-08-12 21:06 UTC, t3hf1gm3nt requested changes
Got some comments and requested changes, mainly to the DKC3 yaml

2022-08-12 21:06 UTC, t3hf1gm3nt commented on games/__meta__.yaml
> +  Dark Souls III: 15
while I approve of the harsh cut to ALttP personally, im curious as to your reasoning behind the similar halving of Minecraft, OoT, and RL. not necessarily disapproving of those changes though.

i might be biased but feel DKC3 could be bumped up a little more. maybe 20?

2022-08-12 21:13 UTC, t3hf1gm3nt commented
i would like someone who actually knows smz3 to look over the changes for that yaml. im gonna assume Marechal's review for DS3 is sufficient. SM64 looks mostly fine from my end and already left notes for DKC3 and the main weights.

2022-08-13 17:51 UTC, ScootyPuffJr1 commented on games/Donkey Kong Country 3.yaml
> +    15: 6
These have been updated.

2022-08-13 17:51 UTC, ScootyPuffJr1 commented on games/Donkey Kong Country 3.yaml
> +    100: 4
These have been updated.

2022-08-13 17:51 UTC, ScootyPuffJr1 commented on games/Donkey Kong Country 3.yaml
> +          local_items: ["Banana Bird"]
I changed them to local items for all seeds.

2022-08-13 17:52 UTC, ScootyPuffJr1 commented on games/Super Mario 64.yaml
> +    courses_only: 2
This have been updated.

2022-08-13 17:56 UTC, ScootyPuffJr1 commented on games/__meta__.yaml
> +  Dark Souls III: 15
At the start of the last async, OoT had 5 of 12 claimed and Minecraft had 4 of 13 while other games had closer to 100%. I think I went too far for Rogue Legacy, though, so I updated that up to 40. I'm fine with DKC3 at 20.

2022-08-13 18:07 UTC, ScootyPuffJr1 commented
I undid my changes for SMZ3 because I think we will need several more changes to it before we roll the next async.

2022-08-13 21:51 UTC, t3hf1gm3nt approved these changes

2022-08-13 21:53 UTC, t3hf1gm3nt commented on games/Donkey Kong Country 3.yaml
> +    15: 6
👍

2022-08-13 21:53 UTC, t3hf1gm3nt commented on games/Donkey Kong Country 3.yaml
> +    100: 4
👍

2022-08-13 21:53 UTC, t3hf1gm3nt commented on games/Donkey Kong Country 3.yaml
> +          local_items: ["Banana Bird"]
👍

2022-08-13 21:53 UTC, t3hf1gm3nt commented on games/Super Mario 64.yaml
> +    courses_only: 2
👍

2022-08-13 21:54 UTC, t3hf1gm3nt commented on games/__meta__.yaml
> +  Dark Souls III: 15
ok, that math seems good to me. good with these changes now

2022-08-23 05:43 UTC, ThePhar commented
Lowering RL chance is fine, so I approve of that. I am going to ping the other game maintainers that haven't looked at this yet so they can review the changed weights or settings.

@PoryGone for DKC3 (Added)
@N00byKing for SM64 (Options Changed)
@espeon65536 for OOT (Weight Lowered)
@KonoTyran for MC (Weight Lowered)
@lordlou for SM (Weight Lowered)
@Jarno458 for TS (Weight Lowered)
@TheCondor07 for SC2 (Weight Increased)

2022-08-23 05:54 UTC, PoryGone commented
I'm fine with what I see wrt DKC3. I trust Figment's judgement on these things (I don't really do asyncs generally).

2022-08-23 08:00 UTC, N00byKing commented
sm64 changes lgtm

2022-08-23 11:28 UTC, ScootyPuffJr1 commented
For what it's worth, the changes for the weights of TS and SM are small because of the large drop in LttP. MC and OOT were cut by about 35% each, TS by 13%, and SM by only 2%. SC2 essentially doubled.

2022-08-23 20:46 UTC, TheCondor07 commented
Sounds good!

2022-08-23 23:56 UTC, lordlou commented
All good for me too!

2022-09-22 12:38 UTC, t3hf1gm3nt approved these changes

2022-09-22 12:39 UTC, merged