Remove some more difficult settings
ArchipelagoMW/AsyncTools pull request #34
Opened 2022-09-27 16:16 UTC by t3hf1gm3nt

Removes weights from insanity ER, moving them to full, and expert item pool/functionality and moves them to hard. Was discussed that these settings are a bit much for a filler yaml and should be left for people to select for customs if they wish.

2022-09-27 16:26 UTC, ScootyPuffJr1 commented
Changes seem fine to me.

2022-09-29 17:57 UTC, alwaysintreble commented
killable thieves should probably be a trigger and ganon_ped should be removed since we have local_ganon_ped. i'd also like to see some shop shuffle options but that might just be me

2022-09-29 18:18 UTC, t3hf1gm3nt commented
I'll admit all these things are outside the scope of my original intention for this update but I'll answer my thoughts anyway.

Killable thieves as a trigger to only be on when enemizer is on? That's something I could agree too.

What do you mean by local Ganon ped? Ganon ped is always local since dungeon prizes are always local

I never play with shop shuffle so I'd have no idea what good options would be for those. I'll leave that to someone with better experience with it to submit a PR, but I could be convinced to have some options in there for it

2022-09-29 18:33 UTC, alwaysintreble commented
i got confused with tfh 🤦

2022-10-01 20:18 UTC, TheT113 commented
I like all of these changes. 👍

2022-10-01 21:20 UTC, ThePhar requested changes

2022-10-01 21:20 UTC, ThePhar commented on games/A Link to the Past.yaml
> +triggers:
This needs to be at the same level as all the other options or it will fail to generate a yaml.

2022-10-02 00:36 UTC, t3hf1gm3nt commented on games/A Link to the Past.yaml
> +triggers:
indented over. look good now?

2022-10-03 23:48 UTC, ScootyPuffJr1 commented
Triggers look good

2022-10-04 04:24 UTC, merged