meta support
ArchipelagoMW/AsyncTools pull request #39
Opened 2022-10-10 01:31 UTC by Berserker66

2022-10-13 01:16 UTC, alwaysintreble commented
i barely understand the original code that Phar wrote but I at least understand the changes being made here and lgtm. Will likely need to revisit meta resolution in core so we can use this for OptionLists, OptionSets and OptionDicts.

2022-10-21 17:29 UTC, ThePhar commented
Let me pull it and give it a whirl.

2022-10-21 17:44 UTC, ThePhar requested changes

2022-10-21 17:44 UTC, ThePhar commented on GenerateMystery.py
>          yaml.dump(mystery, file)
```suggestion
        yaml.dump(dict(mystery), file)
```

Looks like this now outputs the following info in the mystery.yaml file:

```
!!python/object/new:__main__.MysterySettings
dictitems:
  A Link to the Past:
```

which breaks generation (or at least fails the check on the website). Casting to dict seems to prevent that meta data about the class from getting written. Meta looks good though.

2022-10-21 17:45 UTC, ThePhar commented on GenerateMystery.py
>          yaml.dump(mystery, file)
Probably because of the switch from using `mystery = {**mystery, **game_settings` to `mystery.update(game_settings`.

2022-10-21 19:42 UTC, merged